# Generated by Django 5.2.8 on 2025-11-24 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('craft_type', models.CharField(choices=[('wood', 'Woodworking'), ('resin', 'Resin'), ('sign_etching', 'Sign Etching'), ('mixed', 'Mixed / General'), ('other', 'Other')], max_length=50)),
                ('detail_level', models.CharField(choices=[('simple', 'Simple'), ('standard', 'Standard'), ('detailed', 'Detailed')], max_length=20)),
                ('project_type_tags', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('system', 'System'), ('private', 'Private'), ('public', 'Public')], default='system', max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.shop')),
                ('source_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_workflows', to='workflows.workflowrecipe')),
            ],
            options={
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=50)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
    ]
