# Generated by Django 5.2.8 on 2025-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='average_consumable_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Historical average consumable cost for this template.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='average_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Historical average material cost for this template.', max_digits=10, null=True),
        ),
    ]
