# Generated by Django 5.2.8 on 2025-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_of_goods',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of goods at time of sale (materials + consumables + labor if desired).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='gross_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross margin (price - cost_of_goods) at time of sale.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='platform_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marketplace / payment platform fees (e.g. Etsy, Stripe).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual shipping cost paid by the shop.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sales tax collected/remitted for this sale.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy total fees; can be left null if using detailed fee fields.', max_digits=10, null=True),
        ),
    ]
