# Generated by Django 5.2.8 on 2025-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Mark true for high-value / priority customers.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='channel',
            field=models.CharField(blank=True, help_text='Where this customer came from (Etsy, craft fair, Instagram, etc.)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'name'], name='core_custom_shop_id_691d27_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'email'], name='core_custom_shop_id_70c7e7_idx'),
        ),
    ]
