# Generated by Django 5.2.8 on 2025-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_address_line1_customer_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_payment_terms',
            field=models.CharField(default='50/50', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_project_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_units',
            field=models.CharField(default='imperial', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
